# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_auto_20180227_0922'),
        ('users', '0003_auto_20180226_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=700)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.IntegerField(default=None)),
                ('author_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('post_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
